### ISSUE TITLE
S3 Exoscale compliance check not working

### ISSUE THREAD

**Issue by philipgh1** [janoszen/cscanner#15]
Everything is marked compliant, even though there are public readable buckets.

**Comment by janoszen** [comment]
Hi Philip,

Is the bucket public or only certain files? The check, at this time, only
checks the bucket ACL.

Would you suggest going through all files individually?

Janos

**Comment by philipgh1** [comment]
Hi.

Only certain files.

 

Well I think a single public readable file (if big enough) could do enough damage.

 

But don’t worry too much 😊

 

Best regards,

Philip

 

Von: János Pásztor <notifications@github.com> 
Gesendet: Montag, 1. April 2019 15:37
An: janoszen/cscanner <cscanner@noreply.github.com>
Cc: Schögler Philip <Philip.Schoegler@a1.digital>; Author <author@noreply.github.com>
Betreff: Re: [janoszen/cscanner] S3 Exoscale compliance check not working (#15)

 

Hi Philip,

Is the bucket public or only certain files? The check, at this time, only
checks the bucket ACL.

Would you suggest going through all files individually?

Janos
