### ISSUE TITLE
Output all non-compliant firewall rules

### ISSUE THREAD

**Issue by philipgh1** [janoszen/cscanner#17]
An additional resultset of the specific rules, which vioalite the policy to output them as well.

https://github.com/janoszen/cscanner/blob/master/firewall/src/main/java/com/opsbears/cscanner/firewall/FirewallPublicServiceProhibitedRule.java

**Comment by janoszen** [comment]
@philipgh1 I have renamed this task to overhaul the whole CLI interface as it was done in a very quick and dirty manner. I will include your requirements in this.
